kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sept-15-test-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: sept-15-test-dsp-job
    namespace: rhdh-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sept-15-test-dsp-job-role